name: Build and Release Typst PDF

on:
    push:
        branches:
            - master

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Typst
              run: |
                  curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
                  tar -xf typst.tar.xz
                  sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

            - name: Install Fonts (中文 + Consolas)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y fonts-cmu fonts-noto-cjk fonts-linuxlibertine ttf-mscorefonts-installer git unzip
                  git clone https://github.com/pensnarik/consolas-font.git
                  mkdir -p ~/.fonts
                  cp consolas-font/*.ttf ~/.fonts/
                  fc-cache -fv

            - name: Compile Typst to PDF
              run: |
                  make

            - name: Create GitHub Release
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.sha }}
                  name: "Build from commit ${{ github.sha }}"
                  body: |
                      📄 This release was automatically built by GitHub Actions.
                      🔧 Commit: `${{ github.sha }}`
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload PDF to Release
              uses: softprops/action-gh-release@v1
              with:
                  files: main.pdf
                  tag_name: ${{ github.sha }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
